version: '3.8'

services:
    # Kali Linux
    kali:
        build:
            context: ./kali
            dockerfile: dockerfile
        container_name: exert-kali
        depends_on: 
            - postgresql-server
        ports:
            - "4444:4444"
        volumes:
            - ./kali:/app
            - ./kali/metasploit/config:/usr/share/metasploit-framework/config:ro
            - ./kali/metasploit/modules:/root/.msf4/modules
        working_dir: /app
        entrypoint: 
            - /bin/bash
            - /app/entry
        networks:
            - exert-kali-net

    # Kali Linux Rolling
    kali-rolling:
        build:
            context: ./kali-rolling
            dockerfile: dockerfile
        container_name: exert-kali-rolling
        depends_on: 
            - postgresql-server
        ports:
            - "44444:44444"
        volumes:
            - ./kali-rolling:/app
            - ./kali-rolling/metasploit/config:/usr/share/metasploit-framework/config:ro
            - ./kali-rolling/metasploit/modules:/root/.msf4/modules
        working_dir: /app
        entrypoint: 
            - /bin/bash
            - /app/entry
        networks:
            - exert-kali-net

    # Postgresql Server
    postgresql-server:
        image: postgres:13.2
        container_name: exert-kali-postgresql-server
        restart: always
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data/pgdata
        ports:
            - 25432:5432
        environment:
            - POSTGRES_PASSWORD=123456
            - PGDATA=/var/lib/postgresql/data/pgdata
        networks:
            - exert-kali-net

networks:
    exert-kali-net:
        name: exert-kali-net
        driver: bridge
