FROM kalilinux/kali

VOLUME [ "/app" ]

RUN apt -y update && \
    apt -y upgrade && \
    apt -y install \
        procps \
        inetutils-ping \
        metasploit-framework

ENTRYPOINT [ "/app/entry" ]
